# Generated by Django 4.0.1 on 2023-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='location',
            field=models.CharField(default=-2000, max_length=30),
            preserve_default=False,
        ),
    ]
