# Generated by Django 4.0.1 on 2023-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
