# Generated by Django 4.0.1 on 2023-03-31 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbook',
            name='date_logged_out',
        ),
    ]
